#Ref: https://stackoverflow.com/questions/64969644/copy-files-from-gcs-into-a-cloud-run-docker-container-during-build

name: Docker GitHub

on: #[push, pull_request,workflow_dispatch]
  push:
    branches:
      - "develop"

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    env:
      BRANCH: ${GITHUB_REF##*/}
      #SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
      PROJECT_ID: ${{ secrets.PROJECT_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # GCP Authorization by Service Account Key JSON  
      - name: auth
        uses: 'google-github-actions/auth@v1'
        with:
         credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      # Setup gcloud CLI
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
          project_id: ${{ secrets.PROJECT_ID }}
          export_default_credentials: true
      
      # Download the file locally
      #- name: Get_file
      #  run: |-
      #    gsutil cp gs://ccdb34c111111b80-source-bucket/data.txt . 
      #  #gs://ccdb34c111111b80-destination-bucket/


      # Build docker image
      - name: Image_build
        run: |-
          docker build --build-arg GCP_CREDENTIALS="${{ secrets.GCP_CREDENTIALS }}" -t europe-west3-docker.pkg.dev/dbiplake-gft-poc/docker-repo/image .
         #gcr.io/$PROJECT_ID/$SERVICE_NAME .

      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          gcloud auth configure-docker -q

      # Push image to Google Container Registry
      - name: Image_push
        run: |-
          docker push europe-west3-docker.pkg.dev/dbiplake-gft-poc/docker-repo/image 
        #gcr.io/$PROJECT_ID/$SERVICE_NAME
